Tugas 3 Diki Candra P_064
Praktikum-PBW/4b-tugas-3-diki-candra-permana-yuda pull request #1
Opened 2022-03-06 07:06 UTC by diki-yuda

2022-03-07 03:35 UTC, budistwn15 requested changes
Hallo diki, Upload ulang ya , yang diupload kode dengan ekstensi .html, .css, .js ataupuan ekstensi format gambar. Jangan upload file .rar atau .zip

2022-03-08 23:53 UTC, diki-yuda commented
Maaf kang saya baru cek email lagi, nanti akan saya upload ulang

Pada tanggal Sen, 7 Mar 2022 10.35, Budi Setiawan ***@***.***>
menulis:

> ***@***.**** requested changes on this pull request.
>
> Hallo diki, Upload ulang ya , yang diupload kode dengan ekstensi .html,
> .css, .js ataupuan ekstensi format gambar. Jangan upload file .rar atau .zip
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Praktikum-PBW/4b-tugas-3-diki-candra-permana-yuda/pull/1#pullrequestreview-901205438>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX4AQILOZXRCEKQTDVL2FC3U6V2RJANCNFSM5QAXTJLQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> <Praktikum-PBW/4b-tugas-3-diki-candra-permana-yuda/pull/1/review/901205438
> @github.com>
>

2022-03-09 06:44 UTC, diki-yuda commented
Selamat siang kang, saya sudah reupload tugas yang akang suruh. Terima
kasih & Maaf terlambat.

Pada tanggal Sen, 7 Mar 2022 10.35, Budi Setiawan ***@***.***>
menulis:

> ***@***.**** requested changes on this pull request.
>
> Hallo diki, Upload ulang ya , yang diupload kode dengan ekstensi .html,
> .css, .js ataupuan ekstensi format gambar. Jangan upload file .rar atau .zip
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Praktikum-PBW/4b-tugas-3-diki-candra-permana-yuda/pull/1#pullrequestreview-901205438>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX4AQILOZXRCEKQTDVL2FC3U6V2RJANCNFSM5QAXTJLQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> <Praktikum-PBW/4b-tugas-3-diki-candra-permana-yuda/pull/1/review/901205438
> @github.com>
>

2022-03-09 14:31 UTC, budistwn15 approved these changes
Oke diki

2022-03-09 14:31 UTC, merged